version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: laravel_backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www
      - ./docker/.env.docker:/var/www/.env
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_pass
      - APP_ENV=local
      - VITE_DEV_SERVER_URL=http://host.docker.internal:5173
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: react_frontend
    restart: unless-stopped
    environment:
      - VITE_LARAVEL=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./backend:/backend
    depends_on:
      - backend

volumes:
  mysql_data:
