name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Install Backend Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          coverage: none

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: backend/vendor
          key: composer-${{ runner.os }}-${{ hashFiles('backend/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: Install PHP Dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run Laravel Commands
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan migrate --force

  frontend:
    name: Install Frontend Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build